on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - environment: test
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/hello-world
        with:
          who-to-greet: ${{ secrets.MESSAGE }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  reuse:
    uses: ./.github/workflows/reuse.yaml
    needs: hello_world_job
    with:
      message: "Good night"
    secrets: inherit
