on: [push]

jobs:
  plans:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.web.outputs.any_changed }}
      app: ${{ steps.app.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Check if web changed
        id: web
        uses: tj-actions/changed-files@v35
        with:
          files: apps/web/**

      - name: Check if app changed
        id: app
        uses: tj-actions/changed-files@v35
        with:
          files: apps/app/**

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    needs: plans
    environment: test
    if: needs.plans.outputs.web == 'true'
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/hello-world
        with:
          who-to-greet: ${{ secrets.MESSAGE }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  hello_world_job2:
    runs-on: ubuntu-latest
    name: A job to say hello 2
    needs: plans
    environment: test
    if: needs.plans.outputs.app == 'true'
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/hello-world
        with:
          who-to-greet: ${{ secrets.MESSAGE }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  reuse:
    uses: ./.github/workflows/reuse.yaml
    needs: hello_world_job
    with:
      message: "Good night"
    secrets: inherit
