name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello ${{ inputs.message }}.
        shell: bash

  Deployment:
    runs-on: ubuntu-latest
    needs: triage
    environment:
      name: production
      url: https://www.google.com
    steps:
      - run: echo Hello ${{ inputs.message }}.
      - run: sleep 60
      - run: sleep 100
